name: Build and Deploy PDF

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: false
  # REQUIRES ${{ secrets.GH_ACCESS_TOKEN }} defined in secrets

jobs:
  build-deploy-pdf:
    uses: kolosovpetro/github-latex-template/.github/workflows/build-and-deploy-pdf-template.yml@main
    secrets: inherit
    with:
      file_name: 'latex-beamer-template'
      enable_patch_version: true
      runs_on: 'ubuntu-latest'
      workflow_name: 'Build and Deploy PDF'
      build_assets_path: |
        src/latex-beamer-template.tex
        src/latex-beamer-template.bbl
        src/latex-beamer-template.bib
        src/sections
      working_directory_for_latex: 'src'
